### ISSUE TITLE
Design icon buttons for "GitDone" toolbar

### ISSUE THREAD

**Issue by OpenMatt** [OpenMatt/GitDone#4]
**We need nice-looking icons for this browser extension we're building:**
![gitdone 011](https://cloud.githubusercontent.com/assets/1007376/11016264/b4440504-8573-11e5-875e-fd4d06b870ac.png)
- More context on what we're doing and why: 
  https://github.com/OpenMatt/GitDone/blob/master/README.md

**Comment by OpenMatt** [comment]
@lovegushwa @cassiemc @vazquez any chance you might be able to help with this? hoping to ship Sunday aft!

**Comment by OpenMatt** [comment]
Seems like https://fortawesome.github.io/Font-Awesome/ would be a good fit for this.

**Comment by chuckharmston** [comment]
See also:
- https://thenounproject.com/
- http://fontello.com/

**Comment by OpenMatt** [comment]
thanks @chuckharmston !

**Comment by OpenMatt** [comment]
#### Icons to use for version 0.1
- New task icon: https://thenounproject.com/term/paper-plane/98913/
- New project icon https://thenounproject.com/search/?q=folder&i=114012
- Notifications icon: https://thenounproject.com/search/?q=notification&i=125745 or https://thenounproject.com/search/?q=notification&i=149381 or https://thenounproject.com/search/?q=notification&i=45068
- Clone task icon: https://thenounproject.com/search/?q=copy&i=110923 or https://thenounproject.com/search/?q=copy&i=181366 or https://thenounproject.com/search/?q=copy&i=68759
- My projects icon: https://thenounproject.com/search/?q=folders&i=25369

**Comment by aendra-rininsland** [comment]
Here's an icon set I've always wanted to use because it's pretty pretty.

Some examples:

![Basic set](http://www.linea.io/_previews/linea_basic_1.0.jpg)
![Software](http://www.linea.io/_previews/linea_software_1.0.jpg)
![Elaboration](http://www.linea.io/_previews/linea_basic_elaboration_1.0.jpg)

Source: [linea.io](http://www.linea.io/)

**Comment by aendra-rininsland** [comment]
Also, how does the bar live? Is it always part of the browser chrome once enabled? Or does it just replace part of the UI on GitHub.com when a user navigates there? I'd say it'd be good to have either option, but doing it just as a content script (i.e., just overriding and supplementing part of GitHub's API) for now is probably the easiest.

**Comment by aendra-rininsland** [comment]
Another consideration while designing — while this is ultimately targeted towards project managers, it could have a tremendous impact in the FLOSS community by helping project maintainers manage issues better. For instance, I help maintain (or rather, have totally failed to maintain) the massive queue of issues at [masayuki0812/c3](http://github.com/masayuki0812/c3/issues), and any tool that could help me more effectively do that job would be an absolute godsend.

**Comment by OpenMatt** [comment]
@aendrew 
- those icons are gorgeous. love them. 
- re: how does the bar live. our first thought was: part of the chrome. that way, users can file a new issue instantly regardless of where they are, whenever an idea or task strikes. but we'll see what's easiest.
- re: project managers vs. other personae. I totally agree. "project manager" was kind of just a first proxy user type to explain the concept. there are definitely others. I like your use case.

**Comment by OpenMatt** [comment]
@aendrew p.s. @phillipadsmith and I are working on this all day on the 4th floor at MozFest -- could definitely use help if you're keen!

**Comment by OpenMatt** [comment]
@phillipadsmith we can use the icons I've chosen above for 0.1. Then switch to the prettier ones for 0.2
So this one is done for now.
